Climber
chopshop-166/frc-2022 pull request #13
Opened 2022-02-09 01:15 UTC by JoeJanickiChSh

Implement current limits into the Climber subsystem which measures the motors' current and uses that value to stop the motors instead of using limit switches. Three new commands are added: extendCurrent, retractCurrent, and moveCurrent, which implement this new functionality.

2022-02-12 01:03 UTC, msoucy commented
Blocking on chopshop-166/chopshoplib#98

2022-02-13 18:53 UTC, bot190 requested changes
I think we probably want to combine these sets of commands so that if either the limit switches are triggered OR the motor draws too much current we will stop moving.

2022-02-13 18:53 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Climber.java
> +  private final double CURRENT_LIMIT = 1.0; // Current limit in amps, motor stops when this is reached
Real current draw should be closer to 30A so we probably want to make this a bit higher than that.
![image](https://user-images.githubusercontent.com/6110918/153770051-99045cbf-b3ae-4ce7-9884-70fc24225e85.png)

This should also come from the robot map as it depends on the specific robot design.

2022-02-13 20:10 UTC, JoeJanickiChSh commented on src/main/java/frc/robot/subsystems/Climber.java
> +  private final double CURRENT_LIMIT = 1.0; // Current limit in amps, motor stops when this is reached
These changes should be fixed once motor validators get merged into chopshoplib.

2022-02-13 22:58 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Climber.java
> +  private final double CURRENT_LIMIT = 1.0; // Current limit in amps, motor stops when this is reached
Now available if you update chopshoplib's version in `build.gradle` to `2022.5.1`

2022-02-15 23:40 UTC, msoucy requested changes

2022-02-15 23:40 UTC, msoucy commented on src/main/java/frc/robot/maps/GastonMap.java
> +    private final PIDSparkMax rightMotor = new PIDSparkMax(1, MotorType.kBrushless);
These should be declared within the `getLeftTelescopeMap` and its right equivalent.

2022-02-15 23:40 UTC, msoucy commented on src/main/java/frc/robot/maps/GastonMap.java
>      public TelescopeMap getLeftTelescopeMap() {
Are they "climber" maps, or "telescope" maps?

2022-02-15 23:40 UTC, msoucy commented on src/main/java/frc/robot/maps/RobotMap.java
> +            this(new SmartMotorController(new SmartMotorController()), new MockDigitalInput(), new MockDigitalInput());
🚩

2022-02-15 23:40 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Climber.java
> +    return cmd("Extend").onExecute(() -> {
Can these three and their equivalent `retract` commands be abstracted at all? They look very similar, except for the speed.

2022-02-16 00:59 UTC, msoucy submitted a review, later dismissed

2022-02-18 20:25 UTC, jeffaburke requested changes

2022-02-18 20:25 UTC, jeffaburke commented on src/main/java/frc/robot/maps/GastonMap.java
> +        final PIDSparkMax deploymentMotor = new PIDSparkMax(2, MotorType.kBrushless);
Changes your motor ID's

2022-02-18 20:42 UTC, bot190 approved these changes

2022-02-18 20:42 UTC, msoucy approved these changes

2022-02-18 20:48 UTC, jeffaburke approved these changes

2022-02-18 20:48 UTC, merged