Climber
chopshop-166/frc-2022 pull request #19
Opened 2022-02-23 16:38 UTC by JoeJanickiChSh

Remove limit switches from climber and implement rotating arms.

2022-02-25 23:49 UTC, bot190 requested changes

2022-02-25 23:49 UTC, bot190 commented on src/main/java/frc/robot/maps/GastonMap.java
> +        extendMotor.validateCurrent(CURRENT_LIMIT);
This should also set the current limit on the motor controller to help ensure we don't break anything.

2022-02-25 23:49 UTC, bot190 commented on src/main/java/frc/robot/maps/GastonMap.java
> +    private final double CURRENT_LIMIT = 20.0; // The current limit for the climber's motors
This should be specified  per subsystem.

2022-02-25 23:49 UTC, bot190 commented on src/main/java/frc/robot/Robot.java
> +    copilotController.y().whileHeld(parallel("Rotate", leftClimber.rotate(trigger), rightClimber.rotate(trigger)));
We'll have to discuss these with the drive team, but I wonder if using the joysticks would be more intuitive here.

2022-02-25 23:49 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Climber.java
> +  private final double ROTATE_SPEED = 1.0;
Yeah.. lets start these at like .2

2022-02-25 23:49 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Climber.java
> +    double nSpeed = speed.getAsDouble();
This will not work the way you expect since this function is only called when mapping a command to a button.

2022-02-25 23:57 UTC, msoucy requested changes

2022-02-25 23:57 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Climber.java
> +    double nSpeed = speed.getAsDouble();
Is this supposed to be called outside the command? (Hint: probably not)

2022-02-25 23:57 UTC, msoucy commented on src/main/java/frc/robot/maps/RobotMap.java
>      public static class ClimberMap {
It would be lovely if you could split this into a `frc.robot.maps.subsystems.ClimberMap` instead of having all the subsystem maps in one place

2022-02-26 00:57 UTC, msoucy approved these changes, later dismissed

2022-02-26 01:19 UTC, bot190 requested changes
A few more changes please.

2022-02-26 01:19 UTC, bot190 commented on src/main/java/frc/robot/Robot.java
> +    DoubleSupplier climberJoystick = copilotController::getLeftX;
This isn't really necessary, but if you want to have it stored in a variable like this the name should be more specific.

2022-02-26 01:19 UTC, bot190 commented on src/main/java/frc/robot/maps/GastonMap.java
> +        final int EXTEND_LIMIT = 20;
Hmm we probably shouldn't define these twice. I think here we need to put these outside the function and share them.

2022-02-26 01:19 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Climber.java
> +      SmartDashboard.putNumber("Climber Speed", nSpeed);
It would be good to also send the speed we set after the modifiers. You can call get on the motor controller to do so.

2022-02-26 01:39 UTC, msoucy approved these changes

2022-02-26 01:42 UTC, bot190 approved these changes

2022-02-26 01:43 UTC, merged