Intake
chopshop-166/frc-2022 pull request #28
Opened 2022-03-05 19:57 UTC by JoeJanickiChSh

Tune intake speed and current limit

2022-03-05 20:00 UTC, JoeJanickiChSh commented
![image](https://user-images.githubusercontent.com/92126520/156898316-de8ff950-b36e-4e3b-a581-8a11040b881f.png)

2022-03-05 20:01 UTC, bot190 requested changes

2022-03-05 20:01 UTC, bot190 commented on src/main/java/frc/robot/maps/ValkyrieMap.java
> +import edu.wpi.first.wpilibj.CAN;
Remove this please

2022-03-05 20:05 UTC, msoucy approved these changes, later dismissed

2022-03-07 02:36 UTC, bot190 commented on src/main/java/frc/robot/subsystems/BallTransport.java
> +        System.out.println("SIDJAKDHSAJKD");
We don't need this anymore.

2022-03-07 02:36 UTC, bot190 commented on src/main/java/frc/robot/Robot.java
> +        final CommandBase intakeRetract = sequence("Ball transport end",
This may cause problems if both driver and copilot attempt to use the command at the same time. We should definitely test this.

2022-03-08 23:59 UTC, msoucy approved these changes

2022-03-09 00:07 UTC, bot190 approved these changes

2022-03-09 00:07 UTC, merged