Drive rotation commands
chopshop-166/frc-2022 pull request #33
Opened 2022-03-10 00:44 UTC by lilbites21

added 2 commands for later use to rotate the robot and to set its angle.

2022-03-10 03:46 UTC, msoucy requested changes

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public CommandBase setRelitiveAngle(final Rotation2d angle, final double speed) {
Not how "relative" is spelled

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +                setName("Relitive Angle");
Still not how "relative" is spelled

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +                        .abs(pose.getRotation().times(1).getDegrees() - targetRotation.getDegrees()) <= ROTATION_BUFFER;
Why use `.times(1)` when you're just doing math on it?

More importantly, if you overshoot what will happen?

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +                targetRotation = new Rotation2d(pose.getRotation().times(1).getDegrees() + angle.getDegrees());
If you're just getting a value from the rotation you don't need `.times(1)` here.

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +            private Rotation2d targetRotation;
Since this entire variable is set once, why not create it with `thisDrive` up above?

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +                speed2 *= Math.signum(angle.getDegrees());
This math can be done up above with `thisDrive` instead of as a member.

2022-03-10 03:46 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public CommandBase setAbsoluteAngle(final Rotation2d angle, final double speed) {
All comments on `setRelativeAngle` also apply here.

Are the functions similar enough that you can extract common logic?

2022-03-10 03:52 UTC, bot190 requested changes
We probably want to use a PID controller to get us to a given angle long term. But for now we can probably get away with a bang-bang controller. That is, rotate towards the target but if we overshoot by too much we need to re-evaluate what direction we need to rotate. Maybe each time we do this we reduce our rotational speed so we're less likely to rotate past the target.

2022-03-10 03:52 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +                return Math.abs(pose.getRotation().times(1).getDegrees() - angle.getDegrees()) <= ROTATION_BUFFER;
What happens if we were to rotate past the desired angle by accident (rotating to fast)?

2022-03-10 03:52 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +            private double speed2 = speed;
I would prefer to change the argument name to `aSpeed` instead of making this `speed2`

2022-03-10 03:52 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public CommandBase setRelitiveAngle(final Rotation2d angle, final double speed) {
```suggestion
    public CommandBase setRelativeAngle(final Rotation2d angle, final double speed) {
```

2022-03-15 23:04 UTC, msoucy commented
Deprecated in favor of the autonomous-test branch

2022-03-15 23:04 UTC, closed without merging