New Gearing
chopshop-166/frc-2022 pull request #49
Opened 2022-09-26 15:06 UTC by JoeJanickiChSh

Increases speed for the new gearing on the intake. Also adds some flags to disable subsystems in the robot map.

2022-09-26 15:08 UTC, JoeJanickiChSh commented
Whoops turns out I changed the wrong value for the speed.

2022-09-26 16:22 UTC, bot190 reviewed
Doh!

2022-09-26 16:22 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Intake.java
> +    private static final double DEPLOY_EXTEND_SPEED = 0.5;
We can probably increase this even more.

2022-10-07 20:56 UTC, msoucy approved these changes

2022-10-08 15:56 UTC, bot190 requested changes
Let's also lower the current limit significantly.

2022-10-18 13:19 UTC, bot190 approved these changes
We ended up using the 30A current limit at Governor's Cup. There's still a bunch of friction in the slides.

2022-10-18 13:19 UTC, merged